use_frameworks!

platform :ios, '9.0'

target 'react-native-micoup-image-picker_Example' do
  pod 'MCPMicoupImagePicker', :path => '../'

  target 'react-native-micoup-image-picker_Tests' do
    inherit! :search_paths

    
  end
end
